### ISSUE TITLE
Add new questions and solutions

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#1]
More questions and their solutions can be added
Refer [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending a PR

**Comment by ananya0504** [comment]
Can you send the link to the repository where I can some questions? Also, on what topic have the questions have to be based upon?

**Comment by Vishruth-S** [comment]
Questions can be from any topic related to competitive coding (eg Data structures and Algorithms). 
Can be of any difficulty (even beginner level )
You can find questions in websites like [Hackerrank](https://www.hackerrank.com/), [geeksforgeeks](https://www.geeksforgeeks.org/l), [https://codechef.com/](url).  
You may also create your own questions and provide a solution.  
Please refer contributing.md for more details

**Comment by ananya0504** [comment]
Thanks a lot!

**Comment by div-bargali** [comment]
Hey @Vishruth-S , I added solution to "Sherlock and valid strings" problem from Hackerrank.
Please review the PR #24

**Comment by Vishruth-S** [comment]
@div-bargali  As mentioned in the pr review, please add a bit of logic/explanation to your code.

**Comment by jayadevvasudevan** [comment]
can i contribute to this bro

**Comment by subhakr11droy** [comment]
Added new Leetcode Hard problem and solution. Please check

**Comment by Vishruth-S** [comment]
@subhakr11droy  Done and merged 👍

**Comment by amiecroteau** [comment]
Can I go ahead and contribute?

**Comment by Niharika-Arora** [comment]
@Vishruth-S Added Hackerrank problem and solution. Please check #122

**Comment by TejasPodutwar** [comment]
Hey @Vishruth-S I'd added the alternative solution for Electronic shop 
Could you u please review PR #151 ??

**Comment by uV3301** [comment]
Hey @Vishruth-S Made a PR #186
Added an interviewBit problem with solution.
Hope you check that.

**Comment by Vishruth-S** [comment]
@uV3301  Merged 👍

**Comment by Siddhant-K-code** [comment]
Can I Add Following Leetcode Problem's Solution in C++:

* 1311 Get Watched Videos By Your Friends
* 546 Remove Boxes
* 507 Perfect Number
* 12 Integer To Roman
* 11 Container With Most Water
* 10 Regular Expression Matching
* 8 String To Integer
* 7 Reverse Integer
* 6 ZigZag Conversion
* 2 Add Two Numbers

**Comment by Vishruth-S** [comment]
@Siddhant-K-code  Sure you can. Make sure your solutions are well documented with comments. Also read [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and follow the steps mentioned there. As long as your PR follows these guidelines, you're good to go

Happy Contributing 😃

**Comment by IPSITA2000** [comment]
Hello ! Can I add  my python solution for REPLESX , codechef October challenge  , under the Hacktoberfest challenge ?

**Comment by Vishruth-S** [comment]
@IPSITA2000  Sure you can 😃 Just be sure to read  [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and follow the guidelines mentioned there. As long as your PR follows these guidelines, you're good to go 😄

**Comment by lio2011** [comment]
I sent PR check #404

**Comment by amiecroteau** [comment]
Added a Java problem and solution from HackerRank #409

**Comment by neha07kumari** [comment]
Can I add "Cats and a Mouse"  or "Number Line Jumps" Questions and solutions from Hackerrank Algorithms . @Vishruth-S

**Comment by Vishruth-S** [comment]
@neha07kumari Both these problems are already present (Number line jumps is same as Kangaroo). If you have a solution to these which you feel has  a significantly different logic than the ones already existing, you may add that and send a PR.
Alternatively, you may add problems and solutions from other websites which are currently not there.

(Please read [Contributing guidelines](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending any PR)

**Comment by Vishruth-S** [comment]
@lio2011 , @amiecroteau  Merged 👍
