### ISSUE TITLE
Add Codeforces problems and solutions

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#190]
It would be great if we can have some more interesting problems and their solutions from [Codeforces](https://codeforces.com/) ✨ 

Preferred difficulty level: Easy/Medium/hard (please refrain from adding too beginner/trivial questions)
Refer [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and read all points carefully before sending a Pull request.

Keep this in mind: When adding solutions, ensure that you provide sufficient comments so as to explain the logic used. More emphasis is given on understanding the technique used rather than the code itself 😃 

Happy Contributing 😄

**Comment by waridrox** [comment]
Will be happy to contribute to problems of Codeforces :)

**Comment by Vishruth-S** [comment]
@waridrox Sure go ahead. This is open to anyone. Just be sure to read [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and adhere to all guidelines given there 😃

**Comment by subhakr11droy** [comment]
Hi @Vishruth-S,

Added a Div-1 problem from Codeforces, kindly look into the pr #203 

Thanks,
Shubhakar

**Comment by Vishruth-S** [comment]
@subhakr11droy  Merged 👍

**Comment by babitha667** [comment]
@Vishruth-S  can I add my Codeforces solutions with questions

**Comment by Vishruth-S** [comment]
@babitha667 Sure. Please read [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending a Pull request.

**Comment by babitha667** [comment]
@Vishruth-S  can you please check my contribution #465 , I will add some more from codechef and leetcode if you like my contribution .

**Comment by babitha667** [comment]
@Vishruth-S please review my pull request , I have added the recent Codeforces contest question with explanation and my solution.
