### ISSUE TITLE
Add your solutions

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#2]
You can add your solutions to any of the existing questions.
Refer Contributing.md

**Comment by Saujanya0910** [comment]
Hey @Vishruth-S I would like to make a PR with solution for 'Kangaroo' problem in C++. Can you assign it to me?

**Comment by Vishruth-S** [comment]
Sure it's open to anyone. You can add your own solution :)

**Comment by Saujanya0910** [comment]
Hey, @Vishruth-S I have made a PR at #5 adding a valid solution to the kangaroo problem. Please review and merge it or approve it as hacktoberfest-accepted if you find it all right. Thanks!

**Comment by Vishruth-S** [comment]
@Saujanya0910  Done 👍

**Comment by khush31** [comment]
hey @Vishruth-S I would like to contribute on this issue.

**Comment by TejasPodutwar** [comment]
Hey @Vishruth-S  I would like to provide more efficient solution for the Electronic-shop(Hackerrank problem) with a time complexity of O(nlogn)!! Could you please assign this to me?

**Comment by Vishruth-S** [comment]
@khush31  Sure this issue is open to anyone. Please go through [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and read all points carefully before sending a PR

Happy contributing :)

**Comment by Vishruth-S** [comment]
@TejasPodutwar  As mentioned before, this is open to anyone. So surely you can add your solution. Just number your solution accordingly and add it. Refer [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and make sure you follow all the guidlines.

Happy contributing :)

**Comment by TejasPodutwar** [comment]
Hey @Vishruth-S I'd added the alternative solution for Electronic shop
Could you u please review PR #151 ??

**Comment by Vishruth-S** [comment]
@TejasPodutwar  Merged 👍

**Comment by mihirsood** [comment]
Hey @Vishruth-S. 
I'd love to add the solutions for previous week's Leetcode Contest. Please assign it to me.

**Comment by yamini27** [comment]
Hey @Vishruth-S !
I've added python solution to Codechef XYSTR problem in PR #435 . Please review it and approve it as hacktoberfest-accepted if you think it's alright. Thanks!

**Comment by yamini27** [comment]
Hey @Vishruth-S !
I've added C++ solution to Codechef CHEFSTR1 problem in PR #437  . Please review it and approve it as hacktoberfest-accepted if you think it's alright. Thanks!

**Comment by Vishruth-S** [comment]
@yamini27 Merged #435 , #437  👍
