### ISSUE TITLE
Added codechef practice problems inside codechef solutions

### ISSUE THREAD

**Issue by vismay2303** [Vishruth-S/CompetitiveCode#218]
Pls check my solutions from previous codechef long challenges in codechef random practice problems...Please accept my PR.(Hacktoberfest)

**Comment by Vishruth-S** [comment]
Please don't open issues when adding problems. 
Read [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and make the necessary changes to your PR #215
