### ISSUE TITLE
Add interesting problems and solutions from Hackerearth

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#221]
The `hackerEarth_problems` folder currently has only a very few questions. It would be nice if more interesting questions and their solutions be added from [Hackerearth](https://www.hackerearth.com/) ✨ 

Preferred difficulty level: Easy-Medium/hard (please refrain from adding too beginner/trivial questions)
Refer [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and read all points carefully before sending a Pull request.

Keep this in mind: When adding solutions, ensure that you provide sufficient comments so as to explain the logic used. More emphasis is given on understanding the technique used rather than the code itself 😃 

Happy Contributing 😄

**Comment by KAHund** [comment]
I can work on this!

**Comment by Vishruth-S** [comment]
@KAHund  Sure you can. This is open to anyone. Just be sure to read [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending a PR.

Happy contributing 😃

**Comment by AlexMunoz905** [comment]
I want to contribute, but it wants us to make a problem on the website. I was looking on both [HackerEarth](https://hackerearth.com), and [HackerRank](https://hackerrank.com), but I can't figure out where to create a problem. The only one I could find to make problems was for recruits on HackerEarth. I saw one for making your own competition on HackerRank, but where do we make problems for the challenges? Maybe im missing something obvious 🤔...

**Comment by Vishruth-S** [comment]
@AlexMunoz905  You don't have to create a problem there. You can select any of the existing problems from their "practice" sections and add links to the same here (as mentioned in [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md)). Also it would be preferable if the selected problem is not too easy/trivial.
Feel free to reply here if you have any more doubts regarding this 🙃

**Comment by srajantiwari** [comment]
@Vishruth-S I'll contribute Dynamic Programming or Range queries questions from HackerEarth.

**Comment by ankitsri98** [comment]
@Vishruth-S I'll Contribute Problem On TRIE Data Structure .

**Comment by Vishruth-S** [comment]
@srajantiwari  @ankitsri98  Sure all contributions are welcome as long as they follow the contribution guidelines mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) 😄

**Comment by maverickLez** [comment]
I can work on this! :hand:

**Comment by Vishruth-S** [comment]
@maverickLez  Sure you can. It is open to anyone. Just be sure to read [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending a PR.

Happy contributing 😃

**Comment by ankitsri98** [comment]
Sir i have made a request please have a look at it. I have well explained
the problem .
Thank you for giving me this opportunity.

**Comment by Vishruth-S** [comment]
@ankitsri98  Merged 👍

**Comment by lio2011** [comment]
Hey I have sent pr , check #375

**Comment by maverickLez** [comment]
@Vishruth-S will this PR be counted towards hacktoberfest 2020?

**Comment by Vishruth-S** [comment]
@maverickLez Have you sent a PR already? if yes please mention the number here. 
If you are just asking in general, then yes, this repo is Hacktoberfest labelled so any PR sent here will be counted provided it is approved and merged.
As long as your PR adheres with the guidelines given [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md), it will approved and merged  

Happy contributing 🙃
