### ISSUE TITLE
CodeSignal Advance DP problems

### ISSUE THREAD

**Issue by Ankitcode99** [Vishruth-S/CompetitiveCode#227]
Solutions to advance DP problems like K-Palindrome, paintHouses, maximal square in C++

**Comment by Vishruth-S** [comment]
@Ankitcode99  Sure you can add them and send a PR. Just make sure you read [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and follow the guidelines mentioned  🙃

**Comment by Ankitcode99** [comment]
> 
> 
> @Ankitcode99 Sure you can add them and send a PR. Just make sure you read [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and follow the guidelines mentioned 🙃

Sure @Vishruth-S please just let me know if these contributions would be counted towards hacktoberfest. 😅

**Comment by Vishruth-S** [comment]
Yes they will be counted provided your PR is approved and merged. So if your PR follows all the guidelines mentioned in [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md), it will be approved and merged 😃

**Comment by Vishruth-S** [comment]
I am closing this issue since the same is mentioned in #1 . You can still send a PR if you plan to...
