### ISSUE TITLE
Delete duplicate folder and merge contents

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#234]
There are currently 2 folders for CSES Problems. Copy the contents of `cses_problems` into `CSES_problems` and delete the `cses_problems` folder.
I am not able to do this since both folders automatically merge when cloning on Windows machine.  
So if anyone with Linux OS will be able to do this, then please reply here.

Note: Since this involves deletion and modification of files/folders, it would be better if  only those having prior experience with Git and Github take up this issue. So please reply here if you would like to take up this issue.

**Comment by kingjuno** [comment]
I will do that

**Comment by Vishruth-S** [comment]
@kingjuno  Alright go ahead 👍

**Comment by kingjuno** [comment]
done

**Comment by Vishruth-S** [comment]
Resolved by #253 . Closing this
