### ISSUE TITLE
All binary search problems from Interviewbit

### ISSUE THREAD

**Issue by aalokchaudhary** [Vishruth-S/CompetitiveCode#237]
Code and explanation for all binary search problems at Interviewbit in C++.

**Comment by Vishruth-S** [comment]
@aalokchaudhary  Could you please explain the issue ?

**Comment by aalokchaudhary** [comment]
I have solved 9 out off 11 binary search problems at Interviewbit. So I want to contribute the solutions to those problems along with a simple explanation for each of them.

**Comment by Vishruth-S** [comment]
@aalokchaudhary  Sure you can 😃  There was no need to create a separate issue for that.
You can send  a PR once you're done. Make sure it follows all the guidelines [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) 🙃 

Closing this issue...
