### ISSUE TITLE
Add interesting problems and solutions from Spoj

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#288]
It would be nice if interesting questions and their solutions can be added from [Spoj](https://www.spoj.com/) ✨ 
Create a folder named `Spoj_problems` and add.

Preferred difficulty level: Easy-Medium/hard (please refrain from adding too beginner/trivial questions)
Refer [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and read all points carefully before sending a Pull request.

Keep this in mind: When adding solutions, ensure that you provide sufficient comments so as to explain the logic used. More emphasis is given on understanding the technique used rather than the code itself 😃 

Happy Contributing 😄

**Comment by Surya-Pushpa** [comment]
Hey, please check, i created a PR for the same.

**Comment by Vishruth-S** [comment]
@Surya-Pushpa Merged #453 👍
