### ISSUE TITLE
Add Useful Resources for Competitive Coding

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#327]
A new file [USEFUL_RESOURCES.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/USEFUL_RESOURCES.md) has been created for adding some useful resources that can help with Competitive Programming. ✨ 
Some examples include Articles related to CP/DS & Algo, tips for cracking ACM ICPC/Code Jam etc, Cheatsheets, tips for cracking coding interviews and many more.
If you have got any such links to some resources which you feel would be really useful, you may add them to `USEFUL_RESOURCES.md` 😃 

Alternatively, If you have got something useful but is not a link which can be added (For eg: some code snippet etc), You can create an Issue for adding the same to this repository. 🙃

**Comment by kingjuno** [comment]
I will add some algorithm books

**Comment by alokkumarak** [comment]
Can I Add Some Useful Algorithm and Codes for Data Structure ...?

**Comment by baranwal** [comment]
I have added a link with my PR please check that.

**Comment by Vishruth-S** [comment]
@baranwal Merged 👍

**Comment by baranwal** [comment]
> @baranwal Merged +1

Thanks :smiley:

**Comment by yamini27** [comment]
Hey @Vishruth-S !
I've added a website link to Codewars website in PR #436  . Please review it and approve it as hacktoberfest-accepted if you think it's alright. Thanks!

**Comment by baranwal** [comment]
I have added another link please review my PR.

**Comment by Anish0203** [comment]
Hello @Vishruth-S,
I have added a link to the book in the PR #506 . Please review it and approve it as hacktoberfest-accepted if you think it is a good contribution. Thanks in advance.
