### ISSUE TITLE
Addition of Hackerrank Problem and its solution

### ISSUE THREAD

**Issue by AvinashSubhash** [Vishruth-S/CompetitiveCode#39]
Hey, Can I add a hackerrank solution to this Repository? , If yes, then can you assign me? :-)

**Comment by Vishruth-S** [comment]
@AvinashSubhash  Sure you can add it. 
Please read Contributing.md, everything is clearly mentioned there. 

Closing this issue.  (You needn't have to create a separate issue, You may directly contribute by referring issue  #1)
