### ISSUE TITLE
Solve Sparse Matrix Problem

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#46]
Any solutions or logic to solving the [Sparse Matrix Multiplication](https://github.com/Vishruth-S/CompetitiveCode/blob/main/Misc/SparseMatrix_Multiplication/problem.md) problem is welcome.

When submitting a solution,  Please include comments in your code to explain the logic used. More emphasis is given to the technique used in solving rather than the code itself.

**Comment by zahinekbal** [comment]
@Vishruth-S can i contribute on this issues please assign it to me..

**Comment by Vishruth-S** [comment]
@zahinekbal Sure you can. This problem is open to anyone . Multiple solutions in different languages are welcome :) 
Please ensure that you add the logic used in the form of comments.

**Comment by zahinekbal** [comment]
Ohkkk 😊

**Comment by Mitali-laroia** [comment]
@Vishruth-S Kindly check #183

**Comment by Vishruth-S** [comment]
@Mitali-laroia  Sure I will check your solution and get back to you as soon as I can.

**Comment by Vishruth-S** [comment]
Closing due to lack of further responses.
