### ISSUE TITLE
Add CodeChef problems and solutions

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#49]
It would be great if we can have some interesting problems and their solutions from [CodeChef](https://www.codechef.com/)

Refer [Contribting.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and feel free to add some problems from CodeChef and its solutions.

Keep this in mind: When adding solutions, ensure that you provide sufficient comments so as to explain the logic used. More emphasis is given on understanding the technique used rather than the code itself :)

UPDATE: Since there is a great response, it would be better if the problems added are restricted to easy/medium/hard levels.
Please refrain from adding too beginner/Trivial problems

**Comment by Luv8436** [comment]
Hii @Vishruth-S  assign this issue to me.

**Comment by Vishruth-S** [comment]
@Luv8436  It is open to anyone. Refer Contributing.md

**Comment by Aaditya1978** [comment]
@Vishruth-S I have made a PR to this issue. Please Merge it.

**Comment by Mahendra7985** [comment]
i want to work on this

**Comment by gaurangisinha** [comment]
Hello, @Vishruth-S I would like to contribute to this project.

**Comment by Vishruth-S** [comment]
Please refer [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md)

**Comment by DebadityaPal** [comment]
I have added a solution from CodeChef. Please verify and merge if needed.

**Comment by sadow984** [comment]
Hello @Vishruth-S I want add new problem and it's solution

**Comment by sadow984** [comment]
**Added CodeChef problem and its solution with explanation.** @Vishruth-S please review myPR #101  and merge it, thank you

**Comment by Vishruth-S** [comment]
@sadow984  Done 👍

**Comment by Vishruth-S** [comment]
@DebadityaPal  Could you please refer your PR here if the same has not been merged.

**Comment by Arihant416** [comment]
Hi @Vishruth-S, if I wish to edit a solution or update one, should I just delete the file or create a new file instead ?

**Comment by dikshajoshi18** [comment]
can i contribute in c++?

**Comment by Vishruth-S** [comment]
@dikshajoshi18  Sure you can. Just make sure to read [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending a PR :)

**Comment by Vishruth-S** [comment]
This issue will be closed soon....

**Comment by Vishruth-S** [comment]
Since we've got quite sufficient amount of problems and solutions, I am closing this issue. You may still contribute additional problems and solutions by referring issues #1  or #2
