### ISSUE TITLE
Add the 'Hacktoberfest' topic to this repository.

### ISSUE THREAD

**Issue by augustoaccorsi** [Vishruth-S/CompetitiveCode#589]
Hello, 

Hacktoberfest 2021 is already started and to make this repository visible to people who want to contribute to open-source projects, I request you to Add the Hacktoberfest topic to your repository so that folks know you're participating in Hacktoberfest.

Also, add the Hacktoberfest label to any issues in your repository that are ready for contributors to work on.

### Benefits

- Adding this topic will enrol this repository for Hacktoberfest 2021.
- Any contribution to this repository will be counted for Hacktoberfest.
- Will make this repository visible to more people looking for open-source contributions.

**Comment by Vishruth-S** [comment]
@augustoaccorsi Unfortunately, CP/DSA repositories are excluded from Hacktoberfest. This announcement was made by the hacktoberfest team in their [discord channel](https://discord.gg/hacktoberfest)
![image](https://raw.githubusercontent.com/TLE-MEC/Hack-CP/main/Assets/images/announcement.png)
