### ISSUE TITLE
Improve the Readme

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#60]
The current Readme.md looks very plain and can have the following changes  
1) Adding badges like these: Refer: [shields.io](https://shields.io/)
![label](https://user-images.githubusercontent.com/55310756/95007139-d57b8580-0629-11eb-823a-e519492f2813.png)

2) Adding proper links. (eg: add link to contributing.md file)
3) Add emojis if needed (eg: star)
4) Improving overall readability

**Comment by DevLokCodes** [comment]
can i try to work on it

**Comment by Vishruth-S** [comment]
@DevLokCodes  Sure you can work on it but make sure you will be able to achieve all the points mentioned in the issue.

**Comment by DevLokCodes** [comment]
Have completed the later points of the issue
also have added the static badges 

having some doubts regarding the packages.json used in dynamic badges 
could anyone help me in it 
thanking in advance

**Comment by Purvi9399** [comment]
> Have completed the later points of the issue
> also have added the static badges 
> 
> having some doubts regarding the packages.json used in dynamic badges 
> could anyone help me in it 
> thanking in advance 

Can I help you with it ?
What sort of problems are you facing?

**Comment by wasimafser** [comment]
@Vishruth-S , you have said "adding badges like these", does that mean the exact bagdes you have put as an example? or is there a list of badges required ?

**Comment by Vishruth-S** [comment]
Closing the issue. Merged PR #73
