### ISSUE TITLE
Add LeetCode problems and solutions

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/CompetitiveCode#80]
More problems and solutions from [LeetCode](https://leetcode.com/) can be added in the LeetCode_problems folder.

Preferred Difficulty level: Medium to Hard problems (Easy is also acceptable but please refrain from too beginner/trivial problems)

IMPORTANT: Solutions MUST have proper comments EXPLAINING THE LOGIC USED
Please refer [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) and read all points carefully before sending a PR.

**Comment by Mitali-laroia** [comment]
@Vishruth-S Pls,check #82 .

**Comment by subhakr11droy** [comment]
I want to add 3 medium and 3 hard leetcode problems. Please assign me this issue :)

**Comment by Ajaydevv** [comment]
can i add a leetcode problem?

**Comment by Vishruth-S** [comment]
Sure anyone is free to add problems but please read [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before making a PR.
Any PR that doesn't adhere to the guidelines given will NOT be accepted.

Happy contributing :)

**Comment by Arihant416** [comment]
Added an alternate solution to Majority element. Kindly Review #112

**Comment by subhakr11droy** [comment]
Hi @Vishruth-S,

Added a leetcode medium problem with proper explanation. kindly look into the pr #150 

Thanks,
Shubhakar

**Comment by Vishruth-S** [comment]
@Arihant416  @subhakr11droy  Merged 👍

**Comment by Vishruth-S** [comment]
Since we've got quite sufficient problems, I am closing this issue,. You may still contribute problems and solutions by referring #1 or #2
